
services:
  app:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/fonts:/usr/share/fonts:ro
      - ./:/app
    working_dir: /app
    command: >
      /bin/bash -c '
        python calendar_notification.py &
        python reply.py
      '
